# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop
require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/IndentArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/AlignHash:
  Enabled: true
  EnforcedColonStyle: table

EndOfLine:
  Enabled: false
