default: &default
  adapter: redis
  url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  adapter: redis
  url: redis://redistogo:94b2e717b57f676e215e4c0ac0d84051@angelfish.redistogo.com:10851/
