default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: he-blog-development

test:
  <<: *default
  database: he-blog-test

production:
  <<: *default
  database: he-blog-production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
